### ISSUE TITLE
how to use from c#

### ISSUE THREAD

**Issue by jasonswearingen** [chairfull/GodotEasyEditorButtons#1]
Hi, in the docs, could you provide some basic info on how to use this from c#  or if it's possible?

thank you

**Comment by chairfull** [comment]
I've not tried Godot's C# and don't think the `#@button` will work, but `_get_editor_buttons():` should work. Just add it to your Node or Resource and make sure it has `@tool` enabled.

**Comment by jasonswearingen** [comment]
okay I have to figure out how to invoke gdscript from csharp.  thank you.
