### ISSUE TITLE
Filenames should be lowercase

### ISSUE THREAD

**Issue by Robert-K** [chairfull/GodotEasyEditorButtons#2]
I'm getting this warning when using the editor buttons:

![image](https://github.com/user-attachments/assets/04e18920-f1da-4380-a54f-753f409f9acb)

I don't see where it requests the file with a lowercase d, but [the style guide suggests snake_case anyways](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#file-names).

Edit: My bad! I was using _@button2d_ instead of _@button2D_!

I feel like there should be some handling for that, and the snake_case point still stands  😉

**Comment by chairfull** [comment]
Good catch. I wasn't aware of the style guide suggestion and didn't get that warning on Linux.

Updated to lowercase.
